repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/trfore/pre-commit
    rev: v1.5.3
    hooks:
      - id: ansible_role_find_unused_variable
      - id: ansible_role_fix_readability
      - id: ansible_role_find_undefined_handlers
      - id: ansible_role_find_unquoted_values
      - id: ansible_role_find_horizontal_when
      # - id: ansible_role_find_empty_files
      - id: ansible_role_find_empty_directories

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.2
    hooks:
      - id: ansible-lint
