name: CD
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]
    paths-ignore:
      - "LICENSE"
      - "README.md"

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: trfore/ansible-role/.github/workflows/deploy_ansible_galaxy.yml@main # remote repo
    secrets:
      API_KEY: ${{ secrets.GALAXY_API_KEY }}
