name: CD
on:
  pull_request:
    branches: [main]
    types: [closed]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual_deploy:
        description: "deploy to ansible galaxy"
        default: false
        required: true
        type: boolean

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true || (github.event_name == 'release' && github.event.action == 'published') || inputs.manual_deploy }}
    uses: trfore/ansible-role/.github/workflows/deploy_ansible_galaxy.yml@main # remote repo
    secrets:
      API_KEY: ${{ secrets.GALAXY_API_KEY }}
