name: Lint Python
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths-ignore:
      - "LICENSE"
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pylint

      - name: Lint using pylint
        run: pylint $(git ls-files '*.py') --disable=C0114
