name: Lint Python
on:
  workflow_call:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pylint

      - name: Lint using pylint
        run: pylint $(git ls-files '*.py') --disable=C0114
